### ISSUE TITLE
store command line args in keychain

### ISSUE THREAD

**Issue by badstreff** [BadStreff/git2jss#2]
Currently each time sync is run the username and password to the JSS need typed in the command line, it would be nice to have the ability to cache them in something like the keychain and verify they are correct so the user doesn't have to keep typing them

**Comment by rderewianko** [comment]
This works, but my feedback is the option of that or would work better. My case being if i run it through a CI runner I can define variables for each of the three categories. In my case I would not be running this on a OSX machine but rather an ubuntu or other linux variant, that supports CI runners already existing.

**Comment by badstreff** [comment]
Thanks for the input, I'm glad to get feed back on this and am not sure how many people will be running it ad-hoc. I'm assuming that most CI platforms support securely storing credentials and them passing them to command line tools?

If that's the case this might not be very high priority.

**Comment by rderewianko** [comment]
That's correct. Jenkins & GitlabCI can both pass environmental variables through. So running it with a variable as part of the command works.

**Comment by badstreff** [comment]
Will re-open if there is a demand
