### ISSUE TITLE
sync.py do_not_verify_ssl

### ISSUE THREAD

**Issue by darklordbrock** [BadStreff/git2jss#24]
When trying to run the sync.py I'm getting the following error when the --do_not_verify_ssl flag is set. This same flag is working with the download.py. 

`./sync.py:288: DeprecationWarning: verify_ssl is deprecated, use ssl=False instead
  async with aiohttp.ClientSession(connector=aiohttp.TCPConnector(verify_ssl=args.do_not_verify_ssl)) as session:
Traceback (most recent call last):
  File "./sync.py", line 330, in <module>
    loop.run_until_complete(main(args))
  File "uvloop/loop.pyx", line 1446, in uvloop.loop.Loop.run_until_complete
  File "./sync.py", line 289, in main
    categories = await get_existing_categories(session, args.url, args.username, args.password, semaphore)
  File "./sync.py", line 281, in get_existing_categories
    return [c.find('name').text for c in [e for e in ET.fromstring(await resp.text()).findall('category')]]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0`

**Comment by badstreff** [comment]
Hey sorry for the late reply, can you check and see if the this is fixed in the dev branch?

**Comment by darklordbrock** [comment]
Thank you for getting back.

I switched to the dev branch and I'm getting a different error using the --do_not_verify_ssl
```
Changed Extention Attributes:  []
Changed Scripts:  []
./sync.py:383: DeprecationWarning: verify_ssl is deprecated, use ssl=False instead
  verify_ssl=args.do_not_verify_ssl)) as session:`
```

**Comment by badstreff** [comment]
Give it a try now!

**Comment by darklordbrock** [comment]
Worked in the Dev branch. Thank you.

**Comment by darklordbrock** [comment]
Will this get merged into the master branch anytime soon?

**Comment by badstreff** [comment]
I would like to eventually have a unit tests in place to catch things, as it is currently dev get merged whenever I determine it looks good. Which probably isn't the best practice. That said, dev has been resolving a large number off issues for people so I will go ahead and merge it now.

**Comment by darklordbrock** [comment]
Thank you!
