### ISSUE TITLE
Not supplying --password produces error

### ISSUE THREAD

**Issue by apizz** [BadStreff/git2jss#31]
From what I understand, you can not supply `--password` in the command to generate a password prompt.  However, when the password is entered in this prompt it appears to not be accepted, as I get the following error:

```
python sync.py --url https://<jss>.com:8443 --username api_git2jss --do_not_verify_ssl
Password: 
Traceback (most recent call last):
  File "sync.py", line 429, in <module>
    loop.run_until_complete(main())
  File "uvloop/loop.pyx", line 1417, in uvloop.loop.Loop.run_until_complete
  File "sync.py", line 385, in main
    session, args.url, args.username, args.password, semaphore)
  File "sync.py", line 355, in get_existing_categories
    auth = aiohttp.BasicAuth(user, passwd)
  File "/Users/ap.orlebeke/.virtualenv/git2jss/lib/python3.7/site-packages/aiohttp/helpers.py", line 127, in __new__
    raise ValueError('None is not allowed as password value')
ValueError: None is not allowed as password value
```

**Comment by badstreff** [comment]
When you get a change can you verify this is still an issue on the latest master? It should be resolved from what I can see.

Thanks @bradschm!

**Comment by apizz** [comment]
Apologies for the delay.  I'm still getting the same error as previously reported.  Even though a password is entered, the script seems to think the password value is 'None'

**Comment by badstreff** [comment]
No worries, have you ran `git pull` to ensure you are on the latest version?

**Comment by apizz** [comment]
Grrr ... this lives in a private repo and I made a silly typo when I updated the sync.py script where it read `password = getpass.getpass()` at line 418 instead of `args.password = getpass.getpass()`.  With this fixed can confirm this is now working again.

Thanks for the help.

**Comment by badstreff** [comment]
No problem! Glad it is working for you!
